---

- name: create docker es configuration working dir
  file:
    path: /root/docker-es
    state: directory

- name: Render dockerfile from template
  template:
    src: dockerfile.j2
    dest: /root/docker-es/dockerfile

- name: Build docker es image
  docker_image:
    name: docker-elastic
    build: 
        path: /root/docker-es
    source: build

- name: Render docker-compose from template
  template:
    src: docker-compose.j2
    dest: /root/docker-es/docker-compose.yml

- name: increase virtual memory
  command: "sudo sysctl -w vm.max_map_count=262144"

- name: Composing docker
  docker_compose:
    project_src: /root/docker-es
    state: present

- debug:
    var: output