---
- name: ufw allow ssh
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: ufw default deny incoming
  ufw:
    default: deny
    direction: incoming

- name: enable ufw
  ufw:
    state: enabled

- name: allow elastic port to ip instance-b
  ufw:
    rule: allow
    proto: tcp
    port: '9200'
    src: 10.130.0.183