---
- name: install Nginx 
  docker_image:
    name: nginx
    source: pull

- name: stop nginx docker
  docker:
    name: docker-nginx
    state: absent

- name: create nginx html working dir
  file:
    path: /var/lib/jenkins/docker-nginx/html
    state: directory

- name: Render html starter from template
  template:
    src: index.j2
    dest: /var/lib/jenkins/docker-nginx/html/index.html

- name: create nginx configuration working dir
  file:
    path: /var/lib/jenkins/docker-nginx/config
    state: directory

- name: Render html starter from template
  template:
    src: default.j2
    dest: /var/lib/jenkins/docker-nginx/config/default.conf

- name: run docker nginx
  command: "docker run --name docker-nginx -p 80:80 -d -v ~/docker-nginx/html:/usr/share/nginx/html nginx"

  
# masih belum setup jenkins sebagai sudoers