---
- name: install Nginx 
  docker_image:
    name: nginx
    source: pull

- name: stop docker-nginx
  docker_container:
    name: docker-nginx
    image: nginx
    state: absent

- name: create nginx html working dir
  file:
    path: /var/lib/jenkins/docker-nginx/html
    state: directory

- name: Render html starter from template
  template:
    src: index.html.j2
    dest: /var/lib/jenkins/docker-nginx/html/index.html

- name: create nginx configuration working dir
  file:
    path: /var/lib/jenkins/docker-nginx/config
    state: directory

- name: Render configuration starter from template
  template:
    src: default.conf.j2
    dest: /var/lib/jenkins/docker-nginx/config/default.conf

- name: Render fullchain.pem starter from template
  template:
    src: fullchain.pem.j2
    dest: /var/lib/jenkins/docker-nginx/config/fullchain.pem

- name: Render privkey.pem starter from template
  template:
    src: privkey.pem.j2
    dest: /var/lib/jenkins/docker-nginx/config/privkey.pem

- name: run docker nginx
  docker_container:
    name: docker-nginx
    image: nginx
    state: started
    restart: yes
    volumes:
        - "/var/lib/jenkins/docker-nginx/html:/usr/share/nginx/html"
        - "/var/lib/jenkins/docker-nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
        - "/var/lib/jenkins/docker-nginx/config/privkey.pem:/home/privkey.pem"
        - "/var/lib/jenkins/docker-nginx/config/fullchain.pem:/home/fullchain.pem"
    ports:
        - "80:80"
        - "9090:9090"
        - "443:443"


# masih belum setup jenkins sebagai sudoers