---
- name: ufw allow ssh
  become: yes
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: create nginx configuration working dir
  become: yes
  file:
    path: /var/lib/jenkins/firewall
    state: directory

- name: Render configuration starter from template
  become: yes
  template:
    src: before.rules.j2
    dest: /var/lib/jenkins/firewall/before.rules

- name: Copy configuration to ufw
  command: "sudo cp /var/lib/jenkins/firewall/before.rules /etc/ufw/"

- name: Enable ufw
  command: "sudo ufw enable"

- name: Reload configuration
  command: "sudo ufw reload"